[package]
name = "huly-cef"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
anyhow = { workspace = true }
cef-ui-util = { git = "https://github.com/hulylabs/cef-ui.git" }

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true }

url = "2.5"

serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
serde_repr = "0.1.20"

futures = "0.3.31"
tungstenite = "0.26.2"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26.2"

crossbeam-channel = "0.5.14"

cef-ui = { git = "https://github.com/hulylabs/cef-ui.git", branch = "update-cef-131" }
