[package]
name = "huly-cef"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
anyhow = { workspace = true }

serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
url = "2.5"
serde_repr = "0.1"
crossbeam-channel = "0.5.14"

cef-ui = { git = "https://github.com/hulylabs/cef-ui.git" }
