[package]
name = "huly-cef-helper"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
anyhow = { workspace = true }
cef-ui-util = { git = "https://github.com/hulylabs/cef-ui.git" }

[dependencies]
cef-ui-helper = { git = "https://github.com/hulylabs/cef-ui.git" }
