name: Rust Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build Huly CEF
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: |
        cargo run --bin huly-cef-build --release -- --profile release
  
  build-manager-image:
    name: Build and Push Huly CEF Manager Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - run: echo VERSION=$(grep '^version =' Cargo.toml | cut -d '"' -f 2) >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.manager
          push: true
          tags: "${{ secrets.DOCKER_USER }}/huly-cef:${{ env.VERSION }},${{ secrets.DOCKER_USER }}/huly-cef:latest"
          platforms: linux/amd64
