name: Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and Test Huly CEF
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Install xvfb
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install -y xvfb

    - uses: actions/setup-node@v4
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: |
        cargo run --bin huly-cef-build --release -- --profile release

    # - name: Launch
    #   run: |
    #     if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
    #       ./target/release/huly-cef-websockets.app/Contents/MacOS/huly-cef-websockets --no-sandbox
    #     elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
    #       xvfb-run -a ./target/release/huly-cef-websockets --no-sandbox
    #     elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
    #       ./target/release/huly-cef-websockets.exe --no-sandbox
    #     fi

    # - name: Test
    #   working-directory: packages/cef-client
    #   run: |
    #     npm i
    #     npm run test

  build-manager-image:
    name: Build and Push Huly CEF Manager Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: true
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - run: echo VERSION=$(grep '^version =' crates/huly-cef-manager/Cargo.toml | cut -d '"' -f 2) >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.manager
          push: true
          tags: "${{ vars.DOCKER_USER }}/huly-cef:${{ env.VERSION }},${{ vars.DOCKER_USER }}/huly-cef:latest"
          platforms: linux/amd64
