name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and Test Huly CEF
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Install xvfb
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install -y xvfb

    - uses: actions/setup-node@v4
      with:
        node-version: '24'

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: |
        cargo run --bin huly-cef-build --release -- --profile release

    - name: Test
      working-directory: packages/cef-client
      run: |
        npm i
        npm run test

    - name: Upload CEF Cache
      if: always()
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: cef-cache-${{ matrix.os }}
        path: |
          ./cefcache
          !./cefcache/Singleton*
