name: Release Huly CEF

on:
  push:
    branches:
      - 'release/v*.*.*'

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version from branch name
        id: version
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          VERSION=${BRANCH_NAME#release/}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Version: ${VERSION}"
      
      - name: Check if release exists
        run: |
          VERSION=${{ steps.version.outputs.version }}   
          if gh release view "$VERSION" > /dev/null 2>&1; then
            echo "Release ${VERSION} already exists, skipping creation."
            exit 1
          fi

          echo "Release ${VERSION} does not exist, proceeding..."
      
      - name: Build Huly CEF
        run: |
          cargo run --bin huly-cef-build --release -- --profile release
      
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts

          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            tar -czf artifacts/huly-cef-macos.tar.gz -C target/release huly-cef-websockets.app
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            tar -czf artifacts/huly-cef-websockets-linux.tar.gz -C target/release huly-cef-websockets cef
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/release/huly-cef-websockets.exe artifacts/huly-cef-websockets.exe
          fi

          ls artifacts
      
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.version.outputs.version }} \
            --title "Huly CEF ${{ steps.version.outputs.version }}" \
            ./artifacts/*.tar.gz
