name: Release Huly CEF

on:
  push:
    branches:
      - 'release/v*.*.*'

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version from branch name
        id: version
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          VERSION=${BRANCH_NAME#release/}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Version: ${VERSION}"
      
      - name: Check if release exists
        run: |
          VERSION=${{ steps.version.outputs.version }}   
          if gh release view "$VERSION" > /dev/null 2>&1; then
            echo "Release ${VERSION} already exists, skipping creation."
            exit 1
          fi

          echo "Release ${VERSION} does not exist, proceeding..."
      
      - name: Build Huly CEF
        run: |
          cargo run --bin huly-cef-build --release -- --profile release
      
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts

          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cd target/release && zip -r ../../artifacts/huly-cef-macos.zip huly-cef-websockets.app
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cd target/release && zip -r ../../artifacts/huly-cef-linux.zip huly-cef-websockets cef
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cd target/release
            powershell -Command "Compress-Archive -Path 'huly-cef-websockets.exe' -DestinationPath '../../artifacts/huly-cef-windows.zip'"
          fi
      
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=${{ steps.version.outputs.version }}

          if gh release view "$VERSION" > /dev/null 2>&1; then
            gh release upload "$VERSION" ./artifacts/*.zip
          else
            gh release create "$VERSION" \
              --title "Huly CEF $VERSION" \
              ./artifacts/*.zip
          fi
